import { MenuItem, Category, SiteSettings } from '../types'

export const DEMO_CATEGORIES: Category[] = [
  { _id: 'cat-1', name: 'Rice Dishes', slug: { current: 'rice-dishes' }, sortOrder: 1 },
  { _id: 'cat-2', name: 'Soups & Stews', slug: { current: 'soups-stews' }, sortOrder: 2 },
  { _id: 'cat-3', name: 'Proteins', slug: { current: 'proteins' }, sortOrder: 3 },
  { _id: 'cat-4', name: 'Snacks', slug: { current: 'snacks' }, sortOrder: 4 },
  { _id: 'cat-5', name: 'Drinks', slug: { current: 'drinks' }, sortOrder: 5 },
]

export const DEMO_MENU_ITEMS: MenuItem[] = [
  {
    _id: 'item-1',
    name: 'Jollof Rice',
    slug: { current: 'jollof-rice' },
    category: DEMO_CATEGORIES[0],
    description: 'Nigeria\'s most iconic dish — smoky, well-seasoned tomato rice cooked to perfection. Served with your choice of protein.',
    price: 2500,
    extraPortionPrice: 1200,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Jollof Rice' },
    isAvailable: true,
    isFeatured: true,
    tags: ['Bestseller'],
  },
  {
    _id: 'item-2',
    name: 'Egusi Soup',
    slug: { current: 'egusi-soup' },
    category: DEMO_CATEGORIES[1],
    description: 'Rich and hearty ground melon seed soup cooked with assorted meat, stockfish, and fresh leafy vegetables.',
    price: 3000,
    extraPortionPrice: 1500,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Egusi Soup' },
    isAvailable: true,
    isFeatured: true,
    tags: ['Popular'],
  },
  {
    _id: 'item-3',
    name: 'Pounded Yam',
    slug: { current: 'pounded-yam' },
    category: DEMO_CATEGORIES[0],
    description: 'Smooth, stretchy pounded yam made from the finest white yam tubers. The perfect partner for any Nigerian soup.',
    price: 1500,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Pounded Yam' },
    isAvailable: true,
    isFeatured: true,
    tags: [],
  },
  {
    _id: 'item-4',
    name: 'Peppered Goat Meat',
    slug: { current: 'peppered-goat-meat' },
    category: DEMO_CATEGORIES[2],
    description: 'Tender, slow-cooked goat meat tossed in our signature spicy pepper sauce. A true Nigerian classic.',
    price: 3500,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Peppered Goat Meat' },
    isAvailable: true,
    isFeatured: true,
    tags: ['Spicy'],
  },
  {
    _id: 'item-5',
    name: 'Fried Rice',
    slug: { current: 'fried-rice' },
    category: DEMO_CATEGORIES[0],
    description: 'Colourful party-style fried rice loaded with vegetables, liver, and prawns. A celebration on your plate.',
    price: 2500,
    extraPortionPrice: 1200,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Fried Rice' },
    isAvailable: true,
    isFeatured: false,
    tags: [],
  },
  {
    _id: 'item-6',
    name: 'Ofe Onugbu (Bitter Leaf Soup)',
    slug: { current: 'bitter-leaf-soup' },
    category: DEMO_CATEGORIES[1],
    description: 'An Igbo classic — bitter leaf soup with cocoyam, assorted meats, and palm oil. Bold and deeply satisfying.',
    price: 3200,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Bitter Leaf Soup' },
    isAvailable: true,
    isFeatured: false,
    tags: [],
  },
  {
    _id: 'item-7',
    name: 'Suya Skewers',
    slug: { current: 'suya-skewers' },
    category: DEMO_CATEGORIES[3],
    description: 'Thinly-sliced beef marinated in yaji spice blend, skewered and grilled over open flame. Served with onions and tomatoes.',
    price: 2000,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Suya Skewers' },
    isAvailable: true,
    isFeatured: false,
    tags: ['Grilled', 'Spicy'],
  },
  {
    _id: 'item-8',
    name: 'Chapman',
    slug: { current: 'chapman' },
    category: DEMO_CATEGORIES[4],
    description: 'Nigeria\'s favourite mocktail — a refreshing mix of Fanta, Sprite, Angostura bitters, cucumber, and fruit.',
    price: 800,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Chapman' },
    isAvailable: true,
    isFeatured: false,
    tags: ['Cold'],
  },
  {
    _id: 'item-9',
    name: 'Moi Moi',
    slug: { current: 'moi-moi' },
    category: DEMO_CATEGORIES[3],
    description: 'Steamed bean pudding made from blended black-eyed peas, peppers, and spices. A beloved Nigerian side dish.',
    price: 1000,
    image: { _type: 'image', asset: { _ref: '', _type: 'reference' }, alt: 'Moi Moi' },
    isAvailable: true,
    isFeatured: false,
    tags: [],
  },
]

export const DEMO_SETTINGS: SiteSettings = {
  restaurantName: 'Naija Kitchen',
  tagline: 'Authentic Nigerian cuisine, made fresh daily with traditional recipes passed down through generations.',
  heroHeadline: 'Authentic Nigerian Cuisine',
  heroSubtext: 'Experience the rich and vibrant flavours of Nigeria, made fresh daily with traditional recipes passed down through generations.',
  heroImage: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
  phoneNumber: '+234 800 000 0000',
  email: 'hello@iyabeji.com',
  whatsappNumber: '+2348000000000',
  address: '12 Adeola Odeku Street, Victoria Island, Lagos, Nigeria',
  openingHours: 'Monday – Friday: 11AM – 10PM\nSaturday – Sunday: 10AM – 11PM',
  socialLinks: {
    instagram: '',
    facebook: '',
    twitter: '',
    tiktok: '',
    youtube: '',
  },
}

export const isSanityConfigured = () => {
  const projectId = import.meta.env.VITE_SANITY_PROJECT_ID
  return projectId && projectId !== 'your_project_id' && projectId.trim() !== ''
}
